### ISSUE TITLE
Project Gradient Method Issue after Rebase

### ISSUE THREAD

**Issue by RPG-Alex** [RPG-Alex/project-julia#12]
Given we had a few PRs together, I rebased the project and there now appears to be an used method in the color_gradient.rs:

```
warning: associated function `new` is never used
  --> src/color_gradient.rs:38:10
   |
35 | impl<const N: usize> ColorGradient<N>
   | ------------------------------------- associated function in this implementation
...
38 |   pub fn new(colors: [Rgba; N], tresholds: [f32; N]) -> Self { Self { colors, tresholds } }
   |          ^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `project-julia` (bin "project-julia") generated 1 warning
```

Its showing through the warning when running 
`cargo check`

It looks like this just hasn't been implemented yet, in which case we need to implement it, but if it was implemented and somehow lost in the rebase that needs to be fixed too.

**Comment by Silzinc** [comment]
As far as I understand it, the compiler just throws a warning because the function is dead code (i.e. unused). I wrote this function to have a standardized constructor in case we want to create other gradients.

If this is really an issue, maybe this function could just be made `const` and used to define `DEFAULT_COLOR_GRADIENT`.

**Comment by RPG-Alex** [comment]
That makes sense. I was going to suggest keeping it as a constructor, but adding the _, but your solution has been implemented and will work too. Closing issue.
